alter table EASYFOOD_COOKBOOK add constraint FK_EASYFOOD_COOKBOOK_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
create index IDX_EASYFOOD_COOKBOOK_ON_IMAGE on EASYFOOD_COOKBOOK (IMAGE_ID);
