alter table EASYFOOD_COOKBOOK add constraint FK_EASYFOOD_COOKBOOK_ON_SHOP foreign key (SHOP_ID) references EASYFOOD_SHOP(ID);
create index IDX_EASYFOOD_COOKBOOK_ON_SHOP on EASYFOOD_COOKBOOK (SHOP_ID);
